baseURL = 'https://www.jeffyang.io/'
languageCode = 'en-us'
title = "jeffyang.io"
copyright = 'Jeff Yang'
theme = 'ritzy'
enableRobotsTXT = true

[outputs]
  home = ['html']
  section = ['html', 'rss']
  page = ['html']

[params]
  author = 'Jeff Yang'
  description = 'Thoughts from a life in progress.'

[markup]
  [markup.highlight]
    noClasses = false
    style = 'pygments'

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
